### ISSUE TITLE
Bug: Subprocess.run() threw java.lang.ArrayStoreException

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/subprocessj#10]
I saw an error
```
2022-02-03 10:27:32.600 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/main/Flaskr/VisualInspectionTwins
2022-02-03 10:27:33.113 ERROR c.k.k.core.context.internal.TestHooker   - ❌ java.lang.ArrayStoreException
	at com.kazurayam.subprocessj.Subprocess.run(Subprocess.java:123)
	at com.kazurayam.subprocessj.Subprocess$run$0.call(Unknown Source)
	at TL_Flaskr.startupFlaskr(TL_Flaskr.groovy:84)
```

Tried print-debugging:

```
CompletedProcess startupFlaskr(File directory, Integer port, Boolean altView = false) {
		Objects.requireNonNull(directory)
		List<String> args = Arrays.asList(
			"docker", "run", "-it",
			"-e", "FLASKR_ALT_VIEW=\"${altView}\"",
			"-p", "${port}:8080",
			"kazurayam/flaskr-kazurayam:${FLASKR_DOCKER_CONTAINER_VERSION}"
			)
			
		println "args: " + args;
		for (arg in args) {
			println arg + " is " + arg.getClass().getName()
		}
		
		File workdir = File.createTempDir()
		CompletedProcess cp = new Subprocess().cwd(workdir).run(args);
		return cp;
	}
```

```
args: [docker, run, -it, -e, FLASKR_ALT_VIEW="false", -p, 3080:8080, kazurayam/flaskr-kazurayam:1.1.0]
docker is java.lang.String
run is java.lang.String
-it is java.lang.String
-e is java.lang.String
FLASKR_ALT_VIEW="false" is org.codehaus.groovy.runtime.GStringImpl
-p is java.lang.String
3080:8080 is org.codehaus.groovy.runtime.GStringImpl
kazurayam/flaskr-kazurayam:1.1.0 is org.codehaus.groovy.runtime.GStringImpl
```

In Groovy, `java.lang.String` and `org.codehause.groovy.runtime.GStringImpl` are used interchangably. But the `java.lang.ProcessBuilder` does not understand `GStringImpl`. ProcessBuilder accepts only String!

**Comment by kazurayam** [comment]
```
		List<String> args = Arrays.asList(
			"docker", "run", "-it",
			"-e", String.format("FLASKR_ALT_VIEW=\"%s\"", altView),
			"-p", String.format("%s:8080", port),
			String.format("kazurayam/flaskr-kazurayam:%s", FLASKR_DOCKER_CONTAINER_VERSION)
			)
```
