### ISSUE TITLE
CommandLocator failed to find the "jq" command

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/subprocessj#33]
On my macbook, the `which` command can find the path of the `jq` command, as follows:
```
$ which jq
/Users/kazuakiurayama/.pyenv/shims/jq
```

But the CommandLocator failed to find the path of the `jq`.

Sample Katalon Studio Test Case:
```
import com.kazurayam.subprocessj.Subprocess
import com.kazurayam.subprocessj.Subprocess.CompletedProcess
import com.kazurayam.subprocessj.CommandLocator
import com.kazurayam.subprocessj.CommandLocator.CommandLocatingResult;

File input = new File("./input.json");
input.text = """{ "one": 1, "two": 2, "three": 3 }""";

// find the path of "jp" command on the current machine
CommandLocatingResult cfr = CommandLocator.find("jq");
println cfr.toString()
assert cfr.returncode() == 0

```

Run result:
```
2024-02-02 17:45:49.849 INFO  c.k.katalon.core.main.TestCaseExecutor   - --------------------
2024-02-02 17:45:49.853 INFO  c.k.katalon.core.main.TestCaseExecutor   - START Test Cases/TC2
<command-locating-result rc="-1">
<command></command>
<stdout></stdout>
<stderr></stderr>
</command-locating-result>

2024-02-02 17:45:50.508 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/TC2 FAILED.
Reason:
Assertion failed: 

assert cfr.returncode() == 0
       |   |            |
       |   -1           false
       <command-locating-result rc="-1">
       <command></command>
       <stdout></stdout>
       <stderr></stderr>
       </command-locating-result>

	at TC2.run(TC2:12)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:144)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:135)
	at TempTestCase1706863544345.run(TempTestCase1706863544345.groovy:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2024-02-02 17:45:50.537 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/TC2 FAILED.
Reason:
Assertion failed: 

assert cfr.returncode() == 0
       |   |            |
       |   -1           false
       <command-locating-result rc="-1">
       <command></command>
       <stdout></stdout>
       <stderr></stderr>
       </command-locating-result>

	at TC2.run(TC2:12)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:448)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:439)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:418)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:410)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:285)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:144)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:135)
	at TempTestCase1706863544345.run(TempTestCase1706863544345.groovy:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2024-02-02 17:45:50.590 INFO  c.k.katalon.core.main.TestCaseExecutor   - END Test Cases/TC2

```

**Comment by kazurayam** [comment]
See #34 

The CommandLocator depends on the runtime value of the environment variable `PATH`.
